services:

  mysql:
    image: mysql:9.4

    container_name: hello-deployment-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3309:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hello-deployment-web

    restart: unless-stopped

    ports:
      - "8001:8000"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: